test

diff --git a/.github/workflows/vyos-rolling-nightly-build.yml b/.github/workflows/vyos-rolling-nightly-build.yml
--- a/.github/workflows/vyos-rolling-nightly-build.yml
+++ b/.github/workflows/vyos-rolling-nightly-build.yml
@@ -27,6 +27,11 @@ on:
         required: true
         type: boolean
         default: false
+      SKIP_SMOKETEST_TPM:
+        description: 'Skip TPM test'
+        required: true
+        type: boolean
+        default: false
       SKIP_SNAPSHOT_S3_UPLOAD:
         description: 'Skip snapshot upload to S3'
         required: true
@@ -128,6 +133,7 @@ jobs:
     needs: build_iso
     runs-on: ubuntu-24.04
     if: ${{ !inputs.SKIP_SMOKETEST_SYSTEM }}
+    continue-on-error: true
     container:
       image: vyos/vyos-build:current
       options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
@@ -147,6 +153,7 @@ jobs:
         run: |
           set -e
           ln -s vyos-${{ needs.build_iso.outputs.build_version }}-generic-amd64.iso build/live-image-amd64.hybrid.iso
+          exit 1
           sudo make test | tee smoketest_make_test.log
       - uses: actions/upload-artifact@v4
         with:
@@ -159,6 +166,7 @@ jobs:
     needs: build_iso
     runs-on: ubuntu-24.04
     if: ${{ !inputs.SKIP_SMOKETEST_CONFIG }}
+    continue-on-error: true
     container:
       image: vyos/vyos-build:current
       options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
@@ -178,6 +186,7 @@ jobs:
         run: |
           set -e
           ln -s vyos-${{ needs.build_iso.outputs.build_version }}-generic-amd64.iso build/live-image-amd64.hybrid.iso
+          exit 1
           sudo make testc | tee smoketest_make_testc.log
       - uses: actions/upload-artifact@v4
         with:
@@ -190,6 +199,7 @@ jobs:
     needs: build_iso
     runs-on: ubuntu-24.04
     if: ${{ !inputs.SKIP_SMOKETEST_RAID1 }}
+    continue-on-error: true
     container:
       image: vyos/vyos-build:current
       options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
@@ -210,6 +220,7 @@ jobs:
           set -e
           ln -s vyos-${{ needs.build_iso.outputs.build_version }}-generic-amd64.iso build/live-image-amd64.hybrid.iso
           sudo make testraid | tee smoketest_make_testraid.log
+          exit 1
       - uses: actions/upload-artifact@v4
         with:
           name: smoketest_make_testraid
@@ -220,7 +231,8 @@ jobs:
   test_encrypted_config_tpm:
     needs: build_iso
     runs-on: ubuntu-24.04
-    if: ${{ !inputs.SKIP_SMOKETEST_RAID1 }}
+    if: ${{ !inputs.SKIP_SMOKETEST_TPM }}
+    continue-on-error: true
     container:
       image: vyos/vyos-build:current
       options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
@@ -248,6 +260,73 @@ jobs:
           retention-days: 30
           if-no-files-found: error
 
+  slack:
+    needs:
+      - build_iso
+    runs-on: ubuntu-24.04
+    if: failure()
+    steps:
+      - uses: actions/download-artifact@v4
+        with:
+          pattern: smoketest_make_*
+      - shell: bash
+        run: ls -al
+      - name: "Slack notification: filter Smoketest failed logs"
+        id: filter_smoketest_failed_logs
+        run: |
+          ls -al
+          for logfile in $(ls smoketest_make_*.log)
+          do
+              echo $logfile
+              cat $logfile | grep '... FAIL' >> ${{ github.workspace }}/smoketest_filtered.log || true
+              cat $logfile | grep 'ERROR -' >> ${{ github.workspace }}/smoketest_filtered.log || true
+              cat $logfile | grep 'Error:' -A12 >> ${{ github.workspace }}/smoketest_filtered.log || true
+          done
+
+      - name: "Slack notification: send to channel"
+        id: send_a_slack_failure_notification
+        uses: slackapi/slack-github-action@v1.25.0
+        with:
+          payload: |
+            {
+              "text": "*VyOS nightly build automation did not succeed*",
+              "attachments": [
+                {
+                  "color": "FF6600",
+                  "fields": [
+                    {
+                      "title": "Repository",
+                      "short": true,
+                      "value": "${{ github.repository }}"
+                    },
+                    {
+                      "title": "Workflow",
+                      "short": true,
+                      "value": "${{ github.workflow }}"
+                    },
+                    {
+                      "title": "Trigger",
+                      "short": true,
+                      "value": "${{ github.event_name }}"
+                    },
+                    {
+                      "title": "Run number",
+                      "short": true,
+                      "value": "${{ github.run_number }}"
+                    },
+                    {
+                      "title": "URL",
+                      "short": false,
+                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                    }
+                  ]
+                }
+              ]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+
   publish:
     needs:
       - test_config_load
@@ -258,7 +337,7 @@ jobs:
     runs-on: ubuntu-24.04
     permissions:
       contents: write
-    if: ${{ !inputs.SKIP_RELEASE_PUBLISHING }}
+    if: ${{ success() && !inputs.SKIP_RELEASE_PUBLISHING }}
     steps:
       - uses: actions/checkout@v4
       - name: Clone vyos-build source code
